### ISSUE TITLE
can't install in serverside

### ISSUE THREAD

**Issue by hisoscream** [kruftt/SmoothArmorScaling#1]
show not found valheim.exe in dedicated server

**Comment by ViperGremory** [comment]
The problem lies in the name of the process that checks the plugin. For the dedicated server, it’s valheim_server.exe and for the client, it’s valheim.exe.
As a temporary solution, you can change the name of the exe file, as well as the data folder and lines in the .bat script, removing ‘server’ from them.
![Screenshot 2024-06-13 034008](https://github.com/kruftt/SmoothArmorScaling/assets/172549783/0ff29353-9c0e-4ef1-86bb-f9fd867a032d)
@kruftt Could you add a check for the original name of the dedicated server (valheim_server.exe)?

**Comment by kruftt** [comment]
Thanks for the notification I will get to this issue in the next day or two as time permits.

**Comment by kruftt** [comment]
After referencing other mods I noticed they aren't targeting the specific process at all, so I have removed this check and pushed the changes to Thunderstore. They should be propagated within the hour. Please let me know if this resolves the issue as I cannot test this on a windows dedicated server with my current setup.

**Comment by ViperGremory** [comment]
> After referencing other mods I noticed they aren't targeting the specific process at all, so I have removed this check and pushed the changes to Thunderstore. They should be propagated within the hour. Please let me know if this resolves the issue as I cannot test this on a windows dedicated server with my current setup.

Tested both mods with standard server file/folder names, issue solved. 
![Screenshot 2024-06-13 081316](https://github.com/kruftt/SmoothArmorScaling/assets/172549783/1f6d03e1-98e5-4f1a-9be9-eb4716f7020c)

**Comment by kruftt** [comment]
> Tested both mods with standard server file/folder names, issue solved. 

Thank you very much for your informative posts and verification!
